{% set name = "colcon-ros-domain-id-coordinator" %}
{% set version = "0.2.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/colcon-ros-domain-id-coordinator-{{ version }}.tar.gz
  sha256: 470ffe85e4f16f861cc4797f7e2fefeb688324749a4bef8a886d3e8b4e75d2c7

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - colcon-core >=0.12.0

test:
  imports:
    - colcon_ros_domain_id_coordinator
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://colcon.readthedocs.io
  summary: Extension for colcon to coordinate different DDS domain IDs for concurrently running tasks.
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - j-rivero
